# Generated by Django 4.1.1 on 2022-09-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tendencia', models.CharField(choices=[('LG', 'Leal e Bom'), ('NG', 'Neutro e Bom'), ('CG', 'Caótico e Bom'), ('LN', 'Leal e Neutro'), ('NN', 'Neutro e Neutro'), ('CN', 'Caótico e Neutro'), ('LE', 'Leal e Mau'), ('NE', 'Neutro e Mau'), ('CE', 'Caótico e Mau')], max_length=20)),
                ('dificuldade', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('CON', models.IntegerField()),
                ('INT', models.IntegerField()),
                ('WIS', models.IntegerField()),
                ('CHA', models.IntegerField()),
                ('caracteristicas', models.TextField(help_text='Perícias, Idiomas, Imunidades...', max_length=200)),
                ('acoes', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
    ]
