# Generated by Django 4.1.1 on 2022-09-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_monster',
            name='acoes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post_monster',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post_monster',
            name='tendencia',
            field=models.CharField(choices=[('LG', 'Leal e Bom'), ('NG', 'Neutro e Bom'), ('CG', 'Caótico e Bom'), ('LN', 'Leal e Neutro'), ('NN', 'Neutro e Neutro'), ('CN', 'Caótico e Neutro'), ('LE', 'Leal e Mau'), ('NE', 'Neutro e Mau'), ('CE', 'Caótico e Mau')], max_length=20),
        ),
    ]
